export const TZ='America/Los_Angeles';
export const HOLD=5*60*1000;
export const COLORS={available:'#26a889',running:'#4967e4',finished:'#f4b94c',unknown:'#a4aebe'};
export const LABELS={available:'Available',running:'In use',finished:'Finished',unknown:'Other / unknown'};
export const NAMES={'50170051':'Washer 1','50170080':'Washer 3','50170075':'Washer 5','50170082':'Washer 7','50170050':'Washer 9','50170052':'Washer 11','50170078':'Washer 13','50170084':'Washer 15','50170068':'Washer 17','50170072':'Washer 19','20483408':'Washer 21','50170055':'Washer 23','50170058':'Dryer 2','50170061':'Dryer 4','50170081':'Dryer 6','50170060':'Dryer 8','50170087':'Dryer 10','50170064':'Dryer 12','50170065':'Dryer 14','50170059':'Dryer 16','50170057':'Dryer 18','50170062':'Dryer 20','50170067':'Dryer 22','50170074':'Dryer 24','50170071':'Dryer 25','50170054':'Dryer 26'};
const formatter=new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23',weekday:'short'});
export function localParts(t){const p=Object.fromEntries(formatter.formatToParts(new Date(t)).map(x=>[x.type,x.value]));return {date:`${p.year}-${p.month}-${p.day}`,hour:+p.hour,minute:+p.minute+(+p.second)/60,weekday:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].indexOf(p.weekday)};}
export function addDays(date,n){return new Date(Date.parse(date+'T12:00:00Z')+n*864e5).toISOString().slice(0,10);}
export function monday(date){const dow=new Date(date+'T12:00:00Z').getUTCDay();return addDays(date,-((dow+6)%7));}
export function parseCSV(text){const lines=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if(c==='\n'&&!quoted){row.push(field.replace(/\r$/,''));if(row.some(Boolean))lines.push(row);row=[];field='';}else field+=c;}if(field||row.length){row.push(field.replace(/\r$/,''));lines.push(row);}if(!lines.length)return [];const headers=lines.shift();return lines.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??''])));}
export function snapshotsFromRows(rows){const batches=new Map();for(const r of rows){const t=Date.parse(r.observed_at_utc);if(!Number.isFinite(t))continue;const key=r.poll_id;let s=batches.get(key);if(!s){s={t,rows:new Map(),id:key};batches.set(key,s);}s.rows.set(r.machine_id,r);}return [...batches.values()].sort((a,b)=>a.t-b.t);}
export function stateFor(r,source='raw'){if(!r)return 'unknown';if(source==='website'){if(r.website_state==='Available')return 'available';if(r.website_state==='Finished')return 'finished';if(r.website_state.startsWith('Running'))return 'running';return 'unknown';}const c=r.raw_lmc_status?.[0];return c==='7'?'available':c==='5'?'finished':['4','1'].includes(c)?'running':'unknown';}
export function intervals(snapshots,now=Date.now()){return snapshots.map((s,i)=>({...s,end:Math.min(s.t+HOLD,snapshots[i+1]?.t??Infinity,now)})).filter(s=>s.end>s.t);}
export function pieces(interval){const result=[];for(let start=interval.t;start<interval.end;){const end=Math.min(interval.end,(Math.floor(start/36e5)+1)*36e5);const p=localParts(start);result.push({...p,start,end,minutes:(end-start)/6e4,x:p.hour*60+p.minute});start=end;}return result;}
export function countStates(s,ids,source){const counts={available:0,running:0,finished:0,unknown:0};for(const id of ids)counts[stateFor(s.rows.get(id),source)]++;return counts;}
export function patternStats(intervals,ids,source,fromDate){const cells=Array.from({length:168},()=>({minutes:0,free:0,busy:0,dates:new Set()}));const days=new Map();for(const s of intervals){const counts=countStates(s,ids,source);if(!ids.length||counts.unknown)continue;for(const p of pieces(s)){if(p.date<fromDate)continue;const c=cells[p.weekday*24+p.hour];c.minutes+=p.minutes;c.free+=(counts.available>0?p.minutes:0);c.busy+=counts.running*p.minutes;c.dates.add(p.date);if(p.hour>=6){let d=days.get(p.date);if(!d){d={date:p.date,weekday:p.weekday,minutes:0,busy:0};days.set(p.date,d);}d.minutes+=p.minutes;d.busy+=counts.running/ids.length*p.minutes;}}}return {cells,days:[...days.values()]};}
export function countdownEvents(snapshots){const events=[];const active=new Map();let excluded=0;for(const s of snapshots){for(const [id,r] of s.rows){const state=stateFor(r,'raw');const previous=active.get(id);if(state==='running'){const seconds=r.adjusted_remaining_seconds===''?NaN:Number(r.adjusted_remaining_seconds);const valid=Number.isFinite(seconds)&&seconds>=0;const prediction=valid?s.t+seconds*1000:null;let cycle=previous;if(!cycle||s.t-cycle.last.t>2*HOLD){if(cycle)excluded++;cycle={first:s.t,predicted:prediction,last:s,reset:false};}else {if(prediction&&cycle.predicted&&prediction-cycle.predicted>120000)cycle.reset=true;cycle.last=s;}active.set(id,cycle);}else if(previous){if(state==='finished'&&s.t-previous.last.t<=2*HOLD&&previous.predicted!==null&&!previous.reset){events.push({id,first:previous.first,predicted:previous.predicted,low:previous.last.t,high:s.t,lowError:(previous.last.t-previous.predicted)/6e4,highError:(s.t-previous.predicted)/6e4});}else excluded++;active.delete(id);}}}return {events:events.reverse(),excluded};}
