import {TZ,HOLD,COLORS,LABELS,NAMES,localParts,addDays,monday,parseCSV,snapshotsFromRows,stateFor,intervals,pieces,countStates,patternStats,countdownEvents} from './analysis.js';
const BASE='https://raw.githubusercontent.com/tetsnaga/laundry-tracker/data/data/';
const $=s=>document.querySelector(s);
const cache=new Map();let snaps=[],inventory=[],catalog=null,loading=false,activeTab='day',lastSuccess=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel=d=>new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
const time=t=>new Date(t).toLocaleTimeString('en-US',{timeZone:TZ,hour:'numeric',minute:'2-digit'});
const stamp=t=>new Date(t).toLocaleString('en-US',{timeZone:TZ,month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const hours=m=>m<60?`${Math.round(m)} min`:`${(m/60).toFixed(1)} hr`;
const idsFor=kind=>inventory.filter(([k])=>kind==='all'||k===kind).map(([,id])=>id);
const machineName=id=>NAMES[id]||`Machine ${id}`;
const allIntervals=()=>intervals(snaps);
const source=()=>$('#source').value;
function hourLabel(h){return h===0?'12a':h===12?'12p':h===24?'12a':`${h%12}${h<12?'a':'p'}`;}
function axis(){return '<div class="time-axis"><div></div><div class="axis">'+[0,3,6,9,12,15,18,21,24].map(h=>`<span style="left:${h/24*100}%">${hourLabel(h)}</span>`).join('')+'</div></div>';}
function empty(text){return `<p class="empty">${escape(text)}</p>`;}
function card(label,value,foot=''){return `<div class="summary-card"><span>${label}</span><strong>${value}</strong><span class="card-foot">${foot}</span></div>`;}
async function readJSON(path,bust){const res=await fetch(BASE+path+(bust?`?v=${Math.floor(Date.now()/60000)}`:''),{cache:'no-cache'});if(!res.ok)throw new Error(`Data request failed (${res.status}).`);return res.json();}
async function refresh(){if(loading)return;loading=true;$('#refresh').disabled=true;$('#refresh').textContent='Refreshing…';try{catalog=await readJSON('index.json',true);const inv=await readJSON('inventory.json',false);inventory=inv.machines.sort((a,b)=>(a[0]===b[0]?parseInt(machineName(a[1]).match(/\d+/)?.[0]||a[1])-parseInt(machineName(b[1]).match(/\d+/)?.[0]||b[1]):a[0]==='washers'?-1:1));const nowDate=localParts(Date.now()).date;const from=[addDays(nowDate,-Math.max(28,+$('#range').value)),addDays($('#date').value||nowDate,-1),addDays($('#week').value||nowDate,-1)].sort()[0];const files=catalog.observation_files.filter(p=>/^observations\/\d{4}-\d{2}-\d{2}\.csv$/.test(p)&&p.slice(13,23)>=from);const lastTwo=catalog.observation_files.slice(-2);let cursor=0;async function worker(){while(cursor<files.length){const f=files[cursor++];if(!cache.has(f)||lastTwo.includes(f)){const res=await fetch(BASE+f+(lastTwo.includes(f)?`?v=${Math.floor(Date.now()/60000)}`:''),{cache:'no-cache'});if(!res.ok)throw new Error(`Observation request failed (${res.status}).`);const rows=parseCSV(await res.text());if(rows.length&&!('raw_lmc_status' in rows[0]))throw new Error('Unexpected CSV format.');cache.set(f,rows);}}}await Promise.all(Array.from({length:Math.min(4,files.length)},worker));snaps=snapshotsFromRows(files.flatMap(f=>cache.get(f)||[]));lastSuccess=Date.now();$('#error').hidden=true;if(catalog.last_poll_status!=='ok'){showError('The last collection attempt failed. Showing the observations saved before it.');}if(!$('#date').value)$('#date').value=nowDate;if(!$('#week').value)$('#week').value=monday(nowDate);const old=$('#machine').value;$('#machine').innerHTML=inventory.map(([,id])=>`<option value="${escape(id)}">${escape(machineName(id))}</option>`).join('');if(old&&idsFor('all').includes(old))$('#machine').value=old;render();}catch(e){showError(`Could not refresh the data. ${e.message} ${snaps.length?'The last loaded history is still shown.':'Use Refresh to try again.'}`);if(!snaps.length){$('#fresh').textContent='Data unavailable';$('#timeline').innerHTML=empty('No history loaded. Please try Refresh.');}else $('#fresh-sub').textContent='Refresh failed · showing previously loaded data';}finally{loading=false;$('#refresh').disabled=false;$('#refresh').textContent='Refresh';}}
function showError(text){$('#error').textContent=text;$('#error').hidden=false;}
function render(){renderSummary();if(activeTab==='day')renderDay();if(activeTab==='patterns')renderPatterns();if(activeTab==='countdown')renderCountdown();}
function renderSummary(){if(!snaps.length){$('#fresh').textContent='No observations yet';return;}const latest=snaps.at(-1),age=Math.max(0,Math.floor((Date.now()-latest.t)/60000));$('#fresh').textContent=`Last observation ${age<1?'just now':`${age} min ago`}`;$('#fresh-sub').textContent=`${stamp(latest.t)} Pacific · ${age>10?'collection is delayed':'checks every minute'}`;const w=countStates(latest,idsFor('washers'),source()),d=countStates(latest,idsFor('dryers'),source());const dateCount=new Set(snaps.map(s=>localParts(s.t).date)).size;$('#summary').innerHTML=card('Washers available',`${w.available}<small>/ ${idsFor('washers').length}</small>`,`${w.running} in use · ${w.finished} finished${w.unknown?' · '+w.unknown+' unknown':''}`)+card('Dryers available',`${d.available}<small>/ ${idsFor('dryers').length}</small>`,`${d.running} in use · ${d.finished} finished${d.unknown?' · '+d.unknown+' unknown':''}`)+card('Finished',`${w.finished+d.finished}<small>machines</small>`,'At the latest observation')+card('History loaded',`${snaps.length}<small>snapshots</small>`,`${dateCount} calendar ${dateCount===1?'day':'days'} · gaps excluded`);}
function renderDay(){const date=$('#date').value,ids=idsFor($('#kind').value),ints=allIntervals();const entries=ints.flatMap(s=>pieces(s).filter(p=>p.date===date).map(p=>({s,p})));const covered=entries.reduce((n,x)=>n+x.p.minutes,0);$('#day-coverage').textContent=`${hours(covered)} observed · ${dateLabel(date)}`;renderTimeline($('#timeline'),ids.map(id=>({name:machineName(id),id,entries})), '#timeline-detail',true);renderAggregate(entries,ids);}
function renderTimeline(container,rows,detailSelector,groups=false){let group='';const fragments=[axis()];let segmentIndex=0;const details=[];for(const item of rows){if(groups){const kind=inventory.find(([,id])=>id===item.id)?.[0];if(kind!==group){fragments.push(`<div class="group-title"><span>${escape(kind||'Machines')}</span><small>${idsFor(kind).length} machines</small></div>`);group=kind;}}const bars=item.entries.map(({s,p})=>{const r=s.rows.get(item.id);if(!r)return '';const state=stateFor(r,source());const title=`${item.name} · ${time(p.start)}–${time(p.end)} · ${LABELS[state]}`;details.push({title,r,s});return `<button class="segment ${state}" style="left:${p.x/1440*100}%;width:${p.minutes/1440*100}%" data-segment="${segmentIndex++}" aria-label="${escape(title)}" title="${escape(title)}"></button>`;}).join('');fragments.push(`<div class="machine-row"><span class="machine-name">${escape(item.name)}</span><div class="track">${bars}</div></div>`);}container.innerHTML=`<div class="timeline-grid">${fragments.join('')}</div>`;container.onclick=e=>{const button=e.target.closest('[data-segment]');if(!button)return;const {title,r,s}=details[+button.dataset.segment];const remaining=r.remaining_min_raw===''?'not reported':`${r.remaining_min_raw} min`;const adjusted=stateFor(r,'raw')==='running'&&r.adjusted_remaining_seconds!==''?`${(Number(r.adjusted_remaining_seconds)/60).toFixed(1)} min`:'not a running countdown';$(detailSelector).textContent=`${title}. Raw remaining: ${remaining}; adjusted: ${adjusted}. Code ${r.raw_lmc_status}. Observed ${stamp(s.t)}.${r.interpretation_note.startsWith('website fallback')?' '+r.interpretation_note+'.':''}`;};}
function renderAggregate(entries,ids){if(!entries.length){$('#aggregate').innerHTML=empty('No observations on this date. Choose a day with recorded history.');return;}const W=1200,H=210,L=38,R=12,T=12,B=32,PW=W-L-R,PH=H-T-B,total=ids.length;const parts=[`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Stacked machine counts over 24 hours">`];for(let i=0;i<=4;i++){const n=Math.round(total*i/4),y=T+PH-(n/total*PH);parts.push(`<line x1="${L}" y1="${y}" x2="${W-R}" y2="${y}" stroke="#e7ecf3"/><text x="${L-9}" y="${y+4}" text-anchor="end" font-size="12" fill="#7b899a">${n}</text>`);}entries.forEach(({s,p},index)=>{const counts=countStates(s,ids,source());let offset=0;for(const state of ['available','running','finished','unknown']){const count=counts[state];if(!count)continue;const x=L+p.x/1440*PW,y=T+PH-(offset+count)/total*PH,w=p.minutes/1440*PW,h=count/total*PH;parts.push(`<rect x="${x}" y="${y}" width="${Math.max(.5,w)}" height="${h}" fill="${COLORS[state]}"/>`);offset+=count;}parts.push(`<rect tabindex="0" role="button" aria-label="${escape(time(p.start)+': '+Object.entries(counts).map(([k,v])=>`${v} ${LABELS[k]}`).join(', '))}" data-count="${index}" x="${L+p.x/1440*PW}" y="${T}" width="${Math.max(1,p.minutes/1440*PW)}" height="${PH}" fill="transparent"><title>${time(p.start)}: ${counts.available} available, ${counts.running} in use, ${counts.finished} finished</title></rect>`);});for(let h=0;h<=24;h+=3)parts.push(`<text x="${L+h/24*PW}" y="${H-7}" text-anchor="${h===0?'start':h===24?'end':'middle'}" font-size="12" fill="#7b899a">${hourLabel(h)}</text>`);parts.push('</svg>');$('#aggregate').innerHTML=parts.join('');const inspect=e=>{const target=e.target.closest('[data-count]');if(!target)return;const {s,p}=entries[+target.dataset.count],c=countStates(s,ids,source());$('#aggregate-detail').textContent=`${time(p.start)}–${time(p.end)}: ${c.available} available · ${c.running} in use · ${c.finished} finished · ${c.unknown} unknown (${ids.length} machines).`;};$('#aggregate').onclick=inspect;$('#aggregate').onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();inspect(e);}};}
function renderPatterns(){
 const kind=$('#pattern-kind').value,ids=idsFor(kind),range=+$('#range').value;
 const from=addDays(localParts(Date.now()).date,-range+1),ints=allIntervals();
 const {cells,days}=patternStats(ints,ids,source(),from),metric=$('#metric').value;
 const weekdays=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
 $('#heat-title').textContent=metric==='free'?`Observed chance of an available ${kind==='washers'?'washer':'dryer'}`:`Average ${kind} in use`;
 $('#heat-legend').textContent=metric==='free'?'Pale 0% → dark 100%':`Pale 0 → dark ${ids.length} in use`;
 const html=['<div class="heat-grid"><div></div>'];
 for(let h=0;h<24;h++)html.push(`<div class="heat-hour">${hourLabel(h)}</div>`);
 cells.forEach((c,i)=>{if(i%24===0)html.push(`<div class="heat-day">${weekdays[Math.floor(i/24)]}</div>`);
  const value=c.minutes?(metric==='free'?c.free/c.minutes:c.busy/c.minutes/ids.length):null;
  const eligible=c.minutes>=90&&c.dates.size>=3;
  const label=value===null?'No observations':metric==='free'?`${Math.round(value*100)}% at least one available`:`${(c.busy/c.minutes).toFixed(1)} of ${ids.length} in use`;
  const rgb=value===null?'':`rgb(${Math.round(230-191*value)},${Math.round(239-161*value)},${Math.round(254-42*value)})`;
  const text=`${weekdays[Math.floor(i/24)]} ${hourLabel(i%24)}: ${label}. ${Math.round(c.minutes)} observed minutes across ${c.dates.size} dates${eligible?'':'; preliminary'}.`;
  html.push(`<button class="heat-cell ${value===null?'empty-cell':eligible?'':'preliminary'}" style="${rgb?'background-color:'+rgb:''}" data-cell="${i}" aria-label="${escape(text)}" title="${escape(text)}"></button>`);
 });html.push('</div>');$('#heatmap').innerHTML=html.join('');
 $('#heatmap').onclick=e=>{const b=e.target.closest('[data-cell]');if(!b)return;const c=cells[+b.dataset.cell];$('#heat-detail').textContent=b.getAttribute('aria-label')+(c.minutes&&c.dates.size<3?' More dates are needed before comparing this slot with other hours.':'');};
 const eligible=cells.map((c,i)=>({...c,index:i})).filter(c=>c.minutes>=90&&c.dates.size>=3);
 if(eligible.length<3){$('#quiet').innerHTML=empty(`Still building a baseline. Each compared hour needs at least 3 observed dates and 90 minutes of coverage. ${eligible.length} of 168 weekly slots qualify so far.`);}
 else {const baseline=eligible.reduce((a,c)=>a+c.busy,0)/eligible.reduce((a,c)=>a+c.minutes,0);
  const quiet=eligible.filter(c=>baseline-c.busy/c.minutes>=.1).sort((a,b)=>a.busy/a.minutes-b.busy/b.minutes).slice(0,4);
  $('#quiet').innerHTML=quiet.length?quiet.map(c=>`<div class="insight"><div>${weekdays[Math.floor(c.index/24)]}, ${hourLabel(c.index%24)}–${hourLabel(c.index%24+1)}<small>${c.dates.size} dates · ${hours(c.minutes)} observed · ${Math.round(c.free/c.minutes*100)}% with a machine available</small></div><strong>${(c.busy/c.minutes).toFixed(1)} in use<small>${(baseline-c.busy/c.minutes).toFixed(1)} below average</small></strong></div>`).join('')+'<p class="method-note">Compared with the observed-time average of eligible hours. Descriptive differences, not a forecast or significance test.</p>':empty('No eligible hours are noticeably quieter than the observed-hour average yet.');
 }
 const qualified=days.filter(d=>d.minutes>=18*60*.7),outliers=[];
 for(let weekday=0;weekday<7;weekday++){const peers=qualified.filter(d=>d.weekday===weekday);if(peers.length<4)continue;const values=peers.map(d=>d.busy/d.minutes).sort((a,b)=>a-b);const quant=q=>{const p=(values.length-1)*q,lo=Math.floor(p);return values[lo]+(values[Math.ceil(p)]-values[lo])*(p-lo);};const q1=quant(.25),q3=quant(.75),cutoff=q1-1.5*(q3-q1);for(const d of peers){const v=d.busy/d.minutes;if(v<cutoff)outliers.push({...d,value:v,median:quant(.5),peers:peers.length});}}
 $('#outliers').innerHTML=outliers.length?outliers.sort((a,b)=>a.value-b.value).slice(0,4).map(d=>`<div class="insight"><div>${dateLabel(d.date)}<small>${hours(d.minutes)} observed between 6am and midnight · ${d.peers} comparable ${weekdays[d.weekday]}s</small></div><strong>${Math.round(d.value*100)}% in use<small>Median: ${Math.round(d.median*100)}%</small></strong></div>`).join(''):empty('No supported outliers yet. A comparison needs at least 4 of the same weekday, each with 70% coverage from 6am to midnight. Longer histories will make this useful.');
 const machine=$('#machine').value,week=monday($('#week').value||localParts(Date.now()).date);
 const weekRows=Array.from({length:7},(_,i)=>{const date=addDays(week,i);return {name:`${weekdays[i]} ${date.slice(5).replace('-','/')}`,id:machine,entries:ints.flatMap(s=>pieces(s).filter(p=>p.date===date).map(p=>({s,p})))};});
 renderTimeline($('#machine-week'),weekRows,'#week-detail');
}

function renderCountdown(){
 const cutoff=Date.now()-28*864e5;const {events,excluded}=countdownEvents(snaps.filter(s=>s.t>=cutoff));
 const overlaps=events.filter(e=>e.lowError<=0&&e.highError>=0).length;
 const median=values=>{if(!values.length)return null;values.sort((a,b)=>a-b);return values.length%2?values[(values.length-1)/2]:(values[values.length/2-1]+values[values.length/2])/2;};
 const uncertainty=median(events.map(e=>(e.high-e.low)/60000));
 $('#countdown-summary').innerHTML=card('Usable finish transitions',events.length,'Raw running → finished observations')+card('Prediction inside finish interval',events.length?`${Math.round(overlaps/events.length*100)}<small>%</small>`:'—',events.length?`${overlaps} of ${events.length} transitions`:'Waiting for observed finishes')+card('Typical observation uncertainty',uncertainty===null?'—':`${uncertainty.toFixed(1)}<small>min</small>`,`${excluded} ambiguous sequences excluded`);
 if(!events.length){$('#countdown-table').innerHTML=empty('No usable running → finished transitions yet. Comparisons will appear as cycles complete. Gaps over 10 minutes, timer extensions, and missed finished states are excluded.');return;}
 const signed=v=>`${v>0?'+':''}${v.toFixed(1)}`;
 $('#countdown-table').innerHTML='<table><thead><tr><th>Machine</th><th>First seen running</th><th>First prediction</th><th>Observed finish interval</th><th>Difference from prediction</th></tr></thead><tbody>'+events.slice(0,100).map(e=>`<tr><td>${escape(machineName(e.id))}</td><td>${stamp(e.first)}</td><td>${stamp(e.predicted)}</td><td>${stamp(e.low)}–${time(e.high)}</td><td>${signed(e.lowError)} to ${signed(e.highError)} min</td></tr>`).join('')+'</tbody></table>';
}

for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>{activeTab=button.dataset.tab;for(const b of document.querySelectorAll('[data-tab]')){b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));}for(const view of document.querySelectorAll('.view'))view.hidden=view.id!==activeTab;render();};
$('#refresh').onclick=refresh;$('#source').onchange=render;$('#kind').onchange=renderDay;$('#date').onchange=refresh;$('#range').onchange=refresh;$('#pattern-kind').onchange=renderPatterns;$('#metric').onchange=renderPatterns;$('#week').onchange=()=>{$('#week').value=monday($('#week').value);refresh();};$('#machine').onchange=renderPatterns;$('#method-toggle').onclick=()=>{$('#method').open=!$('#method').open;$('#method-toggle').setAttribute('aria-expanded',String($('#method').open));if($('#method').open)$('#method').scrollIntoView({behavior:'smooth',block:'nearest'});};
await refresh();setInterval(()=>{if(!document.hidden)refresh();},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-(lastSuccess||0)>60000)refresh();});

const toolLifecycle=new AbortController();
if(document.modelContext?.registerTool){
 try{Promise.resolve(document.modelContext.registerTool({
  name:'get_laundry_summary',title:'Read laundry status',
  description:'Read the latest loaded machine counts and observation timestamp from this dashboard. Does not refresh or change data.',
  inputSchema:{type:'object',properties:{machineType:{type:'string',enum:['all','washers','dryers']}},additionalProperties:false},
  annotations:{readOnlyHint:true,untrustedContentHint:true},
  execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>k!=='machineType')||!['all','washers','dryers'].includes(input.machineType??'all'))throw new Error('machineType must be all, washers, or dryers.');if(!snaps.length)throw new Error('No observations loaded.');const latest=snaps.at(-1),ids=idsFor(input.machineType??'all');return {observedAt:new Date(latest.t).toISOString(),timezone:TZ,statusSource:source(),counts:countStates(latest,ids,source()),snapshotCount:snaps.length,ageMinutes:Math.max(0,Math.floor((Date.now()-latest.t)/60000))};}
 },{signal:toolLifecycle.signal})).catch(()=>{});}catch{}
}
window.addEventListener('pagehide',()=>toolLifecycle.abort(),{once:true});
